markdown: redcarpet
pygments: true
redcarpet:
  extensions: [ "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data" ]

title: Gradle SSH Plugin
tagline: Deploy your App from Gradle
url: https://gradle-ssh-plugin.github.io/

links:
  - title: Getting Started
    url: /getting-started.html
  - title: User Guide
    url: /user-guide.html
  - title: Releases
    url: https://github.com/int128/gradle-ssh-plugin/releases

right_links:
  - title: GitHub
    url: https://github.com/int128/gradle-ssh-plugin

github:
  repo: https://github.com/int128/gradle-ssh-plugin

product:
  version: 1.1.0
