markdown: redcarpet
pygments: true
redcarpet: 
  extensions: [ "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data" ]

title: Gradle SSH Plugin
tagline: 'Fluent Build and Deploy on Gradle'
description: 'Gradle SSH Plugin'
url: 'http://gradle-ssh-plugin.github.io/'

github:
  repo: 'https://github.com/int128/gradle-ssh-plugin'

product:
  version: 0.3.6
