markdown: redcarpet
pygments: true
redcarpet: 
  extensions: [ "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data" ]

title: Gradle SSH Plugin
tagline: 'Seamless Build and Deploy on Gradle'
description: 'Gradle SSH Plugin provides remote command execution and file transfer features for continuous delivery.'
url: 'http://gradle-ssh-plugin.github.io/'

github:
  repo: 'https://github.com/int128/gradle-ssh-plugin'

